[package]
name = "namuPPuli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indicatif = "0.17.1"
dashmap = "5.4.0"
num_cpus = "1.13.1"